// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_2_shot_index from "./routes/2-shot/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $listings_id_ from "./routes/listings/[id].tsx";
import * as $ListingSearch from "./islands/ListingSearch.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/2-shot/index.tsx": $_2_shot_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/listings/[id].tsx": $listings_id_,
  },
  islands: {
    "./islands/ListingSearch.tsx": $ListingSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
